language: node_js
node_js:
# - 12
# - 14
- node
# os:
#  - linux
#  - osx
cache:
  npm: false
  
script:
  - npm run lint
  - npm run build
#  - npm test ## some error in travis?
  - npm run test:e2e:slow
